# SPDX-FileCopyrightText: © 2026 OpenCHAMI a Series of LF Projects, LLC
# SPDX-License-Identifier: MIT

[Container]

# VOLUMES
Volume=/etc/openchami/configs/%N.cfg:/usr/local/etc/%N/%N.cfg:ro,Z
Volume=haproxy-certs.volume:/etc/%N/certs/:ro,z

# PORTS
PublishPort=8081:80
PublishPort=8443:443

# NETWORKS
Network=openchami-external.network
Network=openchami-internal.network
Network=openchami-jwt-internal.network
PodmanArgs=--http-proxy=false
